apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-market-data
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-market-data
  template:
    metadata:
      labels:
        app: consumer-market-data
    spec:
      containers:
      - name: consumer-market-data
        image: thechrisoneil/fintech-app-portfolio-mgr:latest
        env:
        - name: APP_ROLE
          value: "consumer"
        - name: APP_SCRIPT
          value: "consumer-market-data.py"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        - name: KAFKA_CONSUMER_GROUP
          value: "market-data-group"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
