apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-job-1
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink-job-1
  template:
    metadata:
      labels:
        app: flink-job-1
    spec:
      containers:
      - name: flink-job-1
        image: your-dockerhub-repo/kafka-app:latest
        env:
        - name: APP_ROLE
          value: "flink"
        - name: FLINK_JOB
          value: "flink-job-1.py"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "my-cluster-kafka-bootstrap.kafka.svc:9092"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "2Gi"
            cpu: "2"

