apiVersion: flink.apache.org/v1beta1
kind: FlinkDeployment
metadata:
  name: portfolio-recalculator
  namespace: flink-operator
spec:
  flinkVersion: v1_16
  image:
    name: thechrisoneil/portfolio-mgr-flink:latest
  jobManager:
    replicas: 1
    resource:
      memory: "1024m"
      cpu: "1"
  taskManager:
    replicas: 2
    resource:
      memory: "2048m"
      cpu: "2"
  job:
    jarURI: "/app/PortfolioRecalculator.jar"
    parallelism: 4
    upgradeMode: stateless
    args:
      - --kafka.bootstrap.servers=my-cluster-kafka-bootstrap:9092
      - --input.topic=user-transactions
      - --output.topic=user-portfolio
