apiVersion: v1
kind: Service
metadata:
  name: producer-transaction-sim-service
  namespace: kafka
spec:
  selector:
    app: producer-transaction-sim
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9092
