apiVersion: v1
kind: Service
metadata:
  name: fintech-service
spec:
  selector:
    app: fintech-app-portfolio-mgr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
