apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.7.1   # Supported version
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false  # Plain listener does not use TLS
      - name: tls
        port: 9093
        type: internal
        tls: true   # TLS listener uses TLS
    resources:
      requests:
        memory: 2Gi
        cpu: 500m
    storage:
      type: persistent-claim
      class: standard
      size: 10Gi
  zookeeper:
    replicas: 3
    resources:
      requests:
        memory: 1Gi
        cpu: 500m
    storage:
      type: persistent-claim
      class: standard
      size: 5Gi
  entityOperator:
    topicOperator: {}
    userOperator: {}
