name: CI/CD Pipeline for Kubernetes on AWS

on:
  push:
    branches:
      - main

jobs:
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Log in to Docker Hub
  #       run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push Docker image
    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fintech-app-portfolio-mgr:latest ./app
        docker push ${{ secrets.DOCKER_USERNAME }}/fintech-app-portfolio-mgr:latest

    # Step 4: Configure AWS CLI
    - name: Configure AWS CLI
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Step 5: Set up kubectl
    - name: Set Up Kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        kubectl version --client

    # Step 6: Configure kubeconfig
    - name: Update Kubeconfig
      run: |
        aws eks update-kubeconfig --region us-east-1 --name ${{ secrets.EKS_CLUSTER_NAME }}

    # Step 7: Deploy Strimzi Operator (if not already deployed)
    - name: Deploy Strimzi Operator
      run: |
        kubectl apply -f app/k8s/strimzi/strimzi-operator.yaml
        kubectl wait --for=condition=Available --timeout=300s deployment/strimzi-operator -n kafka


    # Step 8: Deploy Kafka Cluster
    - name: Create Kafka Cluster
      run: |
        kubectl apply -f app/k8s/strimzi/kafka-cluster.yaml
        kubectl wait kafka/my-cluster --for=condition=Ready --timeout=300s -n kafka
        
    # Step 9: Create Kafka Topics
    - name: Create Kafka Topics
      run: |
        kubectl apply -f app/k8s/strimzi/kafka-topics.yaml

    # Step 10: Deploy Application
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f app/k8s/deployment.yaml
        kubectl apply -f app/k8s/service.yaml
